version: '3'
services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /workspace/node_modules
    environment:
      - NODE_ENV=development
  php:
    container_name: php_server
    image: php:7.4-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8082:80"
